### ISSUE TITLE
Question: Showing ProgressDialog without Thread ?

### ISSUE THREAD

**Issue by YordanYanakiev** [theilgazcode/FGX#1]
Hello.
Is it possible to show with the newest version of FGX a progress dialog without need of thread ?
( like it was working in version 0.6.x ) ?

**Comment by theilgaz** [comment]
Hello there.

This is a repack for Delphi 10.3 (Rio).

You should check out the original repo from [here](https://github.com/ms301/FGX-FireMonkey).

**Comment by YordanYanakiev** [comment]
Well.. I am with 10.3.1 (Rio) and I would like to work the way it was in the previous versions (outside/without additional threads).
Is it possible ?
