### ISSUE TITLE
please for 10.4 too

### ISSUE THREAD

**Issue by WillianBotacini** [theilgazcode/FGX#3]

**Comment by emrahozten** [comment]
After compiling the component in Delphi 10.4, make the following changes in the FGX.Helpers.Andorid.pas file.

procedure ShowDialog(ADialog: JDialog; const ADialogID: Integer);
begin
 // if IsGingerbreadDevice then
    MainActivity.showDialog(ADialogID, ADialog);
 // else
    ADialog.show;
end;

procedure HideDialog(ADialog: JDialog; const ADialogID: Integer);
begin

//  if IsGingerbreadDevice then
  //begin
    MainActivity.dismissDialog(ADialogID);
    MainActivity.removeDialog(ADialogID);
 // end
 // else
    ADialog.dismiss;
end;


If you disable these lines the component will work in Delphi 10.4.

**Comment by theilgaz** [comment]
Hi there, 
In 2021, I believe that there is no Gingerbread (Android 2.3) device live anymore. So I directly removed condition from showing and hiding functions.

I fixed this in #4 but I didn't test it. Please let me know if it occurs any error. Thanks.
